"""redesigned_schema

Revision ID: 9e2693de160c
Revises: 
Create Date: 2026-06-17 03:41:44.240514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e2693de160c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='sessionstatus'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('pump_tag', sa.String(length=100), nullable=True),
    sa.Column('format_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('uploading', 'uploaded', 'extracting', 'extracted', 'failed', name='documentstatus'), nullable=False),
    sa.Column('num_pages', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entities_session_tag', 'equipment_entities', ['session_id', 'tag'], unique=False)
    op.create_table('document_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('layout_text', sa.Text(), nullable=True),
    sa.Column('tables_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_path', sa.String(length=512), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('extraction_quality', sa.Enum('full_text', 'partial_text', 'image_only', name='extractionquality'), server_default='full_text', nullable=False),
    sa.Column('page_type', sa.String(length=20), server_default='content', nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_documents',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['equipment_entities.id'], ),
    sa.PrimaryKeyConstraint('entity_id', 'document_id')
    )
    op.create_table('extracted_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('data_type', sa.Enum('numeric', 'text', 'boolean', 'reference', name='fielddatatype'), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('extracted', 'verified', 'corrected', 'rejected', name='fieldstatus'), nullable=False),
    sa.Column('citation_page', sa.Integer(), nullable=False),
    sa.Column('citation_bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('citation_text', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['equipment_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fields_doc_name', 'extracted_fields', ['document_id', 'field_name'], unique=False)
    op.create_index('ix_fields_doc_section', 'extracted_fields', ['document_id', 'section'], unique=False)
    op.create_table('field_corrections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('original_value', sa.Text(), nullable=False),
    sa.Column('corrected_value', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('corrected_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['extracted_fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_corrections')
    op.drop_index('ix_fields_doc_section', table_name='extracted_fields')
    op.drop_index('ix_fields_doc_name', table_name='extracted_fields')
    op.drop_table('extracted_fields')
    op.drop_table('entity_documents')
    op.drop_table('document_pages')
    op.drop_index('ix_entities_session_tag', table_name='equipment_entities')
    op.drop_table('equipment_entities')
    op.drop_table('documents')
    op.drop_table('sessions')
    # ### end Alembic commands ###
